name: Deploy Backend to EC2 via Docker Compose

on:
  push:
    branches: [ "deploy" ] # Se activa estrictamente al hacer push a la rama deploy según rúbrica

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # 1. Autenticación en Docker Hub usando tus Secrets globales
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 2. Construcción y subida optimizada apuntando a la carpeta correcta
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend             # <--- LE DICE A GITHUB QUE SE MUEVA A LA CARPETA BACKEND
        file: ./backend/Dockerfile     # <--- APUNTA AL DOCKERFILE CORRECTO
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tienda-backend:latest

    # 3. Despliegue en la EC2 mediante SSH aplicando Docker Compose
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_BACKEND_HOST }} 
        username: ec2-user                     
        key: ${{ secrets.EC2_SSH_KEY }}       
        script: |
          # 1. Moverse al directorio del repositorio clonado en tu servidor AWS
          cd /home/ec2-user/tienda-perritos-backend
          
          # 2. Traer el último docker-compose.yml actualizado desde GitHub
          git pull origin deploy
          
          # 3. Descargar la imagen fresca que acabamos de compilar y subir a Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tienda-backend:latest
          
          # 4. Detener y limpiar los contenedores previos
          docker-compose down || true
          
          # 5. Descargar actualizaciones adicionales si existen (ej: mysql)
          docker-compose pull
          
          # 6. Levantar todo el stack en segundo plano
          docker-compose up -d
