name: Deploy Backend to EC2 via Docker Compose

on:
  push:
    branches: [ "deploy" ] # Se activa estrictamente al hacer push a la rama deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # 1. Autenticación en Docker Hub usando tus Secrets globales
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 2. Construcción y subida optimizada apuntando al subdirectorio backend/
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend             # Mapea la carpeta del backend donde está el package.json
        file: ./backend/Dockerfile     # Utiliza tu Dockerfile multi-stage
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tienda-backend:latest

    # 3. Despliegue en la EC2 mediante SSH aplicando Docker Compose
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_BACKEND_HOST }} 
        username: ec2-user                     
        key: ${{ secrets.EC2_SSH_KEY }}       
        script: |
          # 1. Entrar a la ubicación del repositorio en tu AWS EC2
          cd /home/ec2-user/tienda-perritos-backend
          
          # 2. Bajar los cambios que acabamos de subir (el nuevo docker-compose.yml)
          git pull origin deploy
          
          # 3. Descargar la imagen fresca desde Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tienda-backend:latest
          
          # 4. Detener los servicios previos de forma limpia
          docker-compose down || true
          
          # 5. Forzar la descarga de otras imágenes necesarias (como mysql)
          docker-compose pull
          
          # 6. Levantar todo el stack en segundo plano de forma limpia
          docker-compose up -d
